In [52]:
#1.
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

In [49]:
#Yes, there is difference in the data type of variables list_ and array_list.
#Here,are  code to print the data types of both the variables.
a=type(list_)
b=type(array_list) 
print('Type of variable list_ is ',a)
print('Type of variable array_list is ', b)

Type of variable list_ is  <class 'list'>
Type of variable array_list is  <class 'numpy.ndarray'>


In [47]:
#2.
#Data Type of Every element of list_  is:
for i in list_:
    print(type(i))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [54]:
#Data Type of Every element of  array_list is:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [55]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

In [56]:
array_list = np.array(object = list_, dtype = int)

In [42]:
#3.
"""There will  be difference in the data type of the elements present in both the variables, list_ and
arra_list"""

'There will  be no difference in the data type of the elements present in both the variables, list_ and\narra_list'

In [60]:
#print of every element datatype in list_
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [62]:
#print of every element datatype in array_list
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [64]:
#for Q no. 4
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [66]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [67]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
#4. i)
num_array.shape

(2, 3)

In [72]:
#4. ii)
num_array.size

6

In [77]:
#5.
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
#6.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])